# Generated by Django 3.2.7 on 2021-10-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211020_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_creatred',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
